services:
  # service gérant le client 
  client:
    image: node:22  
    ports:
      - "5173:5173"  #port de dévelopement
      - "4173:4173"  #port de pré-production
    volumes:
      - ./code/client:/app  
    working_dir: /app  
    tty: true

  # service gérant le serveur 
  server:
    image: node:22
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    tty: true

  # service gérant le serveur MySQL
  
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-db:/var/lib/mysql
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  
  # service gérant le service mongodb 
  mongodb:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - ./code/server/mongodb:/app
      - ./mongodb-db:/data/db
    working_dir: /app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    
  